server:
  port: 5000


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotelUserService
    username: root
    password: Y@sh81530
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  config:
    import: configserver:http://localhost:5005
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-52510420.okta.com/oauth2/default
      client:
        registration:
          my-internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oang88k0v7Vw2Ybl5d7
            client-secret: OwynAtSITDdOwmvkZe3FiDRZM_ZzJOXd8dj157iXyqeH61n6umU3fMBG55VTCUuu

        provider:
          okta:
            issuer-uri: https://dev-52510420.okta.com/oauth2/default
  redis:
    host: localhost
    port: 6379
    timeout: 10000

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always



resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      ratingHotelRetry:
        max-attempts: 3
        wait-duration: 5s

  ratelimiter:
      instances:
        ratingHotelLimiter:
            limit-for-period: 3
            limit-refresh-period: 4s
            timeout-duration: 1s


okta:
  oauth2:
    issuer: https://dev-52510420.okta.com/oauth2/default
    audience: api://default


#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:5003/eureka/



