server:
  port: 5000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotelUserService
    username: root
    password: Y@sh81530
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect


eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:5003/eureka/


